### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by finestructure** [finestructure/Hummingbird#1]
<img width="1063" alt="video-still" src="https://user-images.githubusercontent.com/65520/48720504-1e85e480-ec20-11e8-8d16-03104b20943f.png">

**Comment by unphased** [comment]
I just want to thank you for creating this project. This is much more responsive and smooth compared to the equivalent functionality that BetterTouchTool provides, which I have used for at least 5 years. 

I cannot live without this now. I need something like this for Windows too...

**Comment by finestructure** [comment]
Glad to hear it’s working well for you! :)
