### ISSUE TITLE
Optionally bring to foreground

### ISSUE THREAD

**Issue by finestructure** [finestructure/Hummingbird#13]
https://twitter.com/roberttt1005/status/1173340125146824704

"I was just wondering if you could add a feature to "move a window to the top" when moving it around? I'm not sure if that's a lot of work, but it'd greatly improve the experience imo."

I believe this means to bring to the foreground. (I first understood "to the top" to mean the top of the screen, i.e. towards the menu bar.)

**Comment by ChasonDeshotel** [comment]
"I actually find it’s a feature that the stacking doesn’t change"

Dude, same! I actually found Hummingbird while trying to disable the "change focus on scrollwheel" crap that Xfce does by default. I saw the setting for hotkey window moving which I totally forgot was a thing and wondered if it existed for MacOS. This has made my day

**Comment by finestructure** [comment]
Having considered this a bit more, I think it's easy enough to simply click or tap on the window you're already hovering over. Adding an extra config for that doesn't feel worth it, to be honest.
