### ISSUE TITLE
Hiding menu bar

### ISSUE THREAD

**Issue by bxsx** [finestructure/Hummingbird#24]
Is it technically possible to hide the menu bar for the app?
Once the hotkeys are configured, I don't really need the icon to be visible all the time.
I know I can use dedicated app for hiding unnecessary icons but I don't want yet another app just to handle one app ;-)
However, I'm not sure if this is possible as there is no icon on the Dock too.

**Comment by finestructure** [comment]
In principle that's possible but just not something that Hummingbird can do at this time :)

I use Bartender to hide unnecessary menu items, that works great!

**Comment by bxsx** [comment]
Yeah, I know Bartender but I'm not really into paying another 15€ for another app just to handle Hummingbird ;)
I don't have experience in developing macOS apps but once you confirmed its technically possible for the Hummingbird, I may work on it if this icon starts to annoy me too much ;-)

**Comment by bxsx** [comment]
EDIT: Haven't tested Bartender for years. Seems I might be interested to invest in this application :) Thanks for reminding!

You can close this ticket for now if you are not interested in implementing it.

**Comment by finestructure** [comment]
I go ahead and close it, it's pretty unlikely ;)
