### ISSUE TITLE
BUG: Hummingbird doesn't work with Magnet app

### ISSUE THREAD

**Issue by bxsx** [finestructure/Hummingbird#25]
Magnet (widely used utility) doesn't recognise moving windows by Hummingbird.

**Comment by finestructure** [comment]
Could be more specific as to what's happening and whether it's an issue with Hummingbird or Magnet? For instance, a screen recording would help. Thanks!

**Comment by bxsx** [comment]
Well, at first I also thought that it's more likely Magnet issue, not Hummingbird but I am not convinced anymore.
There really nothing to screen record here. Simply while moving windows via Hummingbird, Magnet doesn't see this (like you wouldn't move at all). I actually check other tools similar to Magnet, and all of them have the problem with Hummingbird.
I believe its Hummingbird problem as other apps that does the same job as Hummingbird (moving windows) work correctly with Magnet and others. So the problem only occur while using Hummingbird.

**Comment by finestructure** [comment]
So I'm using Moom together with Hummingbird and it's working fine. As far as I know, Magnet is doing the same thing as Moom. EDIT: I wrote "isn't working fine" but of course I meant "it's working fine" 😅 

When you say "windows via Hummingbird, Magnet doesn't see this" it _does_ seem like it is an issue with Magnet? Although I'm not sure what Magnet would need to "see". Moom, for instance, just moves and resizes windows on its own and I don't think it actually cares where windows are - it's placing them on its own.

Maybe there's some functionality of Magnet that I'm not aware of or it's not as similar to Moom as I think?

**Comment by finestructure** [comment]
I'm going to close this for now. Please re-open should you continue to see issues!
