### ISSUE TITLE
Move window entirely with keyboard shortcuts

### ISSUE THREAD

**Issue by chriszrc** [finestructure/Hummingbird#29]
This extension makes it easier to move windows with only mouse keys, but I'm wondering if there's a way, once you have activated the dragging feature on the window to then also re-position the window using the standard directional keys (left/right/etc)?

**Comment by finestructure** [comment]
Hi @chriszrc !

Thanks for raising this but I’m afraid moving windows via cursor keys is not something I’m planning to support with Hummingbird. Sorry about that :)

**Comment by chriszrc** [comment]
@finestructure ok, I understand. Are you aware of any extension that does this? I can't seem to find any :'(

**Comment by finestructure** [comment]
Not specifically but I believe BetterTouchTool could be configured to do so. Hope that helps!

**Comment by vlad-cotfas** [comment]
> @finestructure ok, I understand. Are you aware of any extension that does this? I can't seem to find any :'(

You can use http://rectangleapp.com or there is Moom App as well.

**Comment by finestructure** [comment]
Thanks again for raising the issue - closing this now as part of some housekeeping :)
