### ISSUE TITLE
Activate on just the configured keys

### ISSUE THREAD

**Issue by cfarvidson** [finestructure/Hummingbird#3]
Awesome work with this fork!

I'm used to using a click + modifier key to activate but I'm giving this a try. And I'm kinda liking it. 

I noticed that if I configured the Alt key for move (it should be the same for any key really). If I press alt+some other key the move action triggers.

I think that It would be great if Hummingbird only triggered if *just* the configured keys was active on the keyboard.

**Comment by finestructure** [comment]
Sorry for the very late reply - for some reason my notifications were turned off :/

That's a good point. I've never noticed this, because it doesn't really happen with the double key combos (which happen to be the app's defaults, heh) that I'm using.

I'll have a look into fixing this.

**Comment by finestructure** [comment]
Actually, turns out in the latest versions (perhaps it's been like this for quite a while) almost all key combinations but the default seem to be impacted.

**Comment by finestructure** [comment]
Well, it does work, I just forgot to apply the new modifiers after change. This will be fixed in upcoming 3.0.0-11

**Comment by finestructure** [comment]
Another actually - I believe the actual issue you described was fixed a while back already. HB is checking for modifier keys (from the set of five: shift, control, alt, command, fn) to be set exclusively.

Or do you actually mean that it moves your window if you press, say, Alt-A or some other non-modifier?

**Comment by finestructure** [comment]
I believe this is fixed now. Please re-open if you're still seeing issues!

**Comment by cfarvidson** [comment]
Awesome!
