### ISSUE TITLE
Any way to simulate "real" dragging?

### ISSUE THREAD

**Issue by jason5122** [finestructure/Hummingbird#30]
Hi,

This is just a small issue that I've been having with BetterTouchTool. Using that app, I can drag windows to one of the edges of the screen to have it auto align (mimics Windows behavior). However, "dragging" a window to an edge using Hummingbird doesn't trigger that auto align function. Is there a way to have the move be treated as an actual drag? Thank you!

**Comment by finestructure** [comment]
Housekeeping: I believe this is a duplicate of #19 - please re-open with more details if not!
