### ISSUE TITLE
Unable to build locally

### ISSUE THREAD

**Issue by ehni** [finestructure/Hummingbird#32]
Hi,

I'm unable to build the project and test locally.

### Issue.

I cloned the repository and opened in in Xcode 12.3 (12C33) on a MacBook Pro M1.

I get the following error when building:

```bash
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
version: 0306421
Set: Entry, ":CFBundleVersion", Does Not Exist
Command PhaseScriptExecution failed with a nonzero exit code
```

I'm not experienced with Xcode & MacOS App Development and I haven't found any suitable solution so far. 

### Context

I wanted to contribute and add the functionality to hide the menu bar icon.

The use case is the following:
- User wants to hide the menu icon.
- Next to "Resize from nearest corner" there's a "Hide menu bar icon" setting.
- When the user opens Hummingbird while the menu bar is hidden the preferences are shown automatically. (This could be also the default when the menu bar is shown, currently just nothing happens 🤷‍♂️)
- This would reduce the menu bar icons the user has and leads to a more organised desktop.

I tried to implement this by myself and added some functionality (new Menu setting, new Config Value and logic to not create a menu icon when the value is set) but I'm unable to build and test it.

**Comment by finestructure** [comment]
Hi Robert, it's a bit odd that this should fail but it must the the script build phase that sets the app version for release purposes. This isn't relevant for development or testing and so you should be able to simply delete this. Have a look in the project settings and remove it:

![CleanShot 2020-12-21 at 17 58 24@2x](https://user-images.githubusercontent.com/65520/102802014-51c66f00-43b6-11eb-9784-d591ee7a469c.png)

That should get you in building order. Let me know if that helps!

**Comment by ehni** [comment]
Yes that did the trick 😊 Thanks a bunch. I opened a PR now → #33 and will close this issue then
