### ISSUE TITLE
Fix icon consistency for dark theme

### ISSUE THREAD

**Issue by rollecode** [finestructure/Hummingbird#37]
Sorry to say but this bugs the hell out of me 😁 Which one doesn't belong:

![Screen-Shot-2021-06-22-23-12-40 74](https://user-images.githubusercontent.com/1534150/122993374-e9ca0300-d3af-11eb-90aa-2942e4d138eb.png)

Can you change it to be more consistent or add an option for it?

**Comment by finestructure** [comment]
Hah, you should update to the latest version! :)

https://hbird.app

**Comment by rollecode** [comment]
@finestructure Oh nice! I assumed it would auto update but guess not. In the new version there is no menubar icon present at all?

**Comment by finestructure** [comment]
Yes, there is:

![CleanShot 2021-06-23 at 05 30 15@2x](https://user-images.githubusercontent.com/65520/123031202-3b8c8080-d3e4-11eb-8606-d9298899866f.png)

Perhaps you have it disabled?

![CleanShot 2021-06-23 at 05 31 26@2x](https://user-images.githubusercontent.com/65520/123031239-4a733300-d3e4-11eb-811b-2cdf08c2f22a.png)

**Comment by rollecode** [comment]
I had it enabled but it showed up when I ticked it off and on again! Thanks.
