### ISSUE TITLE
Preferences window does not open in the foreground (MacOS 10.13.6 (17G4015))

### ISSUE THREAD

**Issue by ghost** [finestructure/Hummingbird#4]
Opening the Preferences dialog via status bar context menu opens the dialog window without bringing it to the foreground.

## Steps to reproduce:

1. Have enough  windows open so that they cover most of the desktop.
2. Open Preferences from the status bar context menu > **Preferences**.

## Expected result:
Preferences window opens in the foreground and is focused.

## Actual result:
Preferences window opens behind existing windows, is not visible and is not focused.

Reproducible on MacOS 10.13.6 (17G4015)
Version: https://github.com/finestructure/Hummingbird/releases/download/2.0.0/Hummingbird.app.zip

**Comment by finestructure** [comment]
Sorry for the very late reply - for some reason my notifications were turned off :/

I've actually noticed this myself - good to know someone else is bothered by this! :) Thanks for reporting, I'll see if I can fix this.
