### ISSUE TITLE
Not working on macOS Sonoma?

### ISSUE THREAD

**Issue by dmartin** [finestructure/Hummingbird#45]
It may just be an issue with my system, but after upgrading to macOS 14.1.1 (from 13.x) Hummingbird no longer seems to be working.
I'm using the Homebrew cask (have tried removing and reinstalling with no luck), and have Hummingbird.app allowed in the Privacy & Security > Accessibility list.

**Comment by dmartin** [comment]
Never mind! Appears to be the same as <https://github.com/finestructure/Hummingbird/issues/27>.
I wasn't aware that there was a trial period that expired - the preferences window just displayed "Unregistered - click to register" in either case so I figured it was a donationware situation.
Happy to buy a license, but just as a bit of feedback, I think the trial period/expiration status could be clearer.

**Comment by finestructure** [comment]
Ah, glad to hear it's working now! It's been a while but if I remember correctly there's an alert on launch if the trial has expired. Or there should be 😅

Thanks for the feedback and thanks for supporting the app! 🎉
