### ISSUE TITLE
macOS Sequoia compatibility

### ISSUE THREAD

**Issue by fiedl** [finestructure/Hummingbird#48]
- I've just installed Hummingbird on the macOS Sequoia beta `15.0 Beta (24A5320a)`

  ```
  brew tap finestructure/Hummingbird
  brew install finestructure/hummingbird/hummingbird
  ```

- I've authorised Hummingbird in the System Preferences
- I've configured Hummingbird like this:

  <img width="489" alt="Bildschirmfoto 2024-08-22 um 15 37 16" src="https://github.com/user-attachments/assets/2808040b-17a5-41d7-9b35-929902d32872">

- However, using the specified shortcuts, the window cannot be moved and cannot be resized
- Starting the application through the terminal does not yield any errors while trying to move or resize:

  ```
  /Applications/Hummingbird.app/Contents/MacOS/Hummingbird
  ```

- Opening the application preferences yields the following output:

  ```
  /Applications/Hummingbird.app/Contents/MacOS/Hummingbird
  2024-08-22 15:34:24.197 Hummingbird[80038:5675217] +[IMKClient subclass]: chose IMKClient_Legacy
  2024-08-22 15:34:24.197 Hummingbird[80038:5675217] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
  ``` 

Please let me know if I can help you to debug this.

**Comment by finestructure** [comment]
Mmm, mysterious. Typically when users face this problem it goes away at some point after reinstalling / restarting / re-setting the accessibility permissions.

Have you possibly been using Hummingbird before such that the trial period of two weeks might be elapsed?

**Comment by finestructure** [comment]
FWIW, Hummingbird runs fine on Sequoia. I'm running it there.

**Comment by fiedl** [comment]
Thanks for the info!

I've now compiled it with Xcode `Version 16.0 beta 6 (16A5230g)`, which worked fine. 👍
