### ISSUE TITLE
Option to use drag to move/resize windows

### ISSUE THREAD

**Issue by brettinternet** [finestructure/Hummingbird#49]
Hi, would you be willing to consider an option to use drag instead of moving the cursor? This may be a more natural option because windows already use the drag gesture when moving them from the title bar - such as three fingers from a trackpad. This would allow repositioning the cursor with normal movement while the hotkeys are active.

**Comment by finestructure** [comment]
Thanks for your interest in Hummingbird, @brettinternet !

I'll be honest, for me Hummingbird is "feature complete" and all I'll be aiming for now is compatibility with macOS versions.

I've seen that [Moom](https://manytricks.com/moom/) has recently gained the same capabilities (see "Moving and Resizing Isn't a Drag") as Hummingbird (in addition to its other features). Perhaps Moom's authors would be interested in adding that feature?

**Comment by brettinternet** [comment]
Thanks for making all your work available here! I completely understand about the state of this software and thank you for your reply. Maybe it's time for me to pick up Swift :)
