### ISSUE TITLE
Help! Can't compile this

### ISSUE THREAD

**Issue by unphased** [finestructure/Hummingbird#50]
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/7466819d-4499-4db2-8f7f-5792a95c033c">

I'm on Sonoma with Xcode 16.0.

I used BTT's feature for moving windows for a while but I realized it has some weird bugs lately and would like to get Hummingbird working again.

**Comment by finestructure** [comment]
I haven't built Hummingbird in a while but the binary available at https://hbird.app works fine on Sonoma and Sequoia.

**Comment by brettinternet** [comment]
A couple of those files are just missing `import Cocoa`.

**Comment by unphased** [comment]
Thank you. with that I was able to build it.
